### PR TITLE
Another batch of AVX2 intrinsics

### PR DESCRIPTION
**Pull request by jackmott**
I've commented out the two functions that fail in debug mode with a note about it.

### CODE REVIEW

**Comment by BurntSushi** [comment]
@jackmott Thanks! Can you please start rebasing and squashing your changes against current master? For example, the first commit in this PR is the same first commit from your first PR. I squashed your previous PR for you, but the list of commits is getting out of control. :-/

**Comment by BurntSushi** [comment]
(This otherwise looks good to go!)

**Comment by jackmott** [comment]
do you happen to know the git incantations i need to do? if not I'll figure it out eventually

**Comment by BurntSushi** [comment]
@jackmott OK, I just did this one for you to make it simpler. At this point, when you start a new PR, you should be able to do this:

```
$ git checkout master
# Update your local master with BurntSushi/stdsimd
$ git pull origin master --ff-only
$ git checkout -b some-new-branch
# add your new vendor intrinsics, run normal git commit commands
$ git push your-fork some-new-branch
# go to github and submit PR
# once PR is merged, restart
$ git checkout master
$ git pull origin master --ff-only
$ git branch -d some-new-branch
$ git checkout -b another-branch
```

and so on... Basically, the idea is to make each PR contain only the commits relevant to that PR. To do that, you'll need to base new PRs off `master` where `master` contains all of your previously merged PRs.

Note that in the commands above, I used `origin` to refer to `BurntSushi/stdsimd`, but you might have that setup to track your fork. To see the truth, run `git remote -v`.

**Comment by jackmott** [comment]
thank you

**Pull request merged**
